<?php
/**
 * Social and document meta.
 *
 * Open Graph, Twitter cards, canonical, description and image_src. Kept
 * separate from inc/schema.php: that file describes the entity graph for
 * search engines, this one describes the page for anything that unfurls a
 * link. They overlap in content but not in purpose or format.
 *
 * The share card lives at assets/img/social/og-default.jpg and is generated by
 * tools/build-og.ps1. Individual posts override it with their featured image.
 *
 * @package Magenta
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * The description for the current view, trimmed to a sane share length.
 */
function magenta_meta_description(): string {
	$description = '';

	if ( is_singular() && ! is_front_page() ) {
		$post = get_queried_object();
		if ( $post instanceof WP_Post ) {
			$description = has_excerpt( $post ) ? get_the_excerpt( $post ) : wp_strip_all_tags( $post->post_content );
		}
	} elseif ( is_tax() || is_category() || is_tag() ) {
		$description = term_description();
	} elseif ( is_post_type_archive( 'project' ) ) {
		$description = __( 'Printed work produced by Magenta for hotels, restaurants, retailers and agencies across the Cayman Islands.', 'magenta' );
	}

	if ( ! $description ) {
		$description = get_bloginfo( 'description' );
	}

	if ( ! $description ) {
		$description = __( 'Print production and graphic design in Grand Cayman. Menus, packaging, signage and identity for the island\'s hotels, restaurants and agencies.', 'magenta' );
	}

	$description = trim( wp_strip_all_tags( $description ) );

	/**
	 * Filter the meta description.
	 *
	 * @param string $description Description text.
	 */
	return apply_filters( 'magenta_meta_description', wp_trim_words( $description, 32, '' ) );
}

/**
 * The share image for the current view.
 *
 * @return array{url:string,width:int,height:int,alt:string}
 */
function magenta_share_image(): array {
	$default = array(
		'url'    => MAGENTA_URI . '/assets/img/social/og-default.jpg',
		'width'  => 1200,
		'height' => 630,
		'alt'    => sprintf(
			/* translators: %s: site name. */
			__( '%s - print production and graphic design, Grand Cayman', 'magenta' ),
			get_bloginfo( 'name' )
		),
	);

	if ( is_singular() && has_post_thumbnail() ) {
		$id  = get_post_thumbnail_id();
		$src = wp_get_attachment_image_src( $id, 'magenta-16x9' );

		if ( $src ) {
			$alt = get_post_meta( $id, '_wp_attachment_image_alt', true );
			$default = array(
				'url'    => $src[0],
				'width'  => (int) $src[1],
				'height' => (int) $src[2],
				'alt'    => $alt ? $alt : get_the_title(),
			);
		}
	}

	/**
	 * Filter the share image.
	 *
	 * @param array $image Share image url, dimensions and alt text.
	 */
	return apply_filters( 'magenta_share_image', $default );
}

/**
 * The title used when the link is unfurled - the document title without the
 * trailing site-name tail, which reads as noise inside a card.
 */
function magenta_share_title(): string {
	if ( is_front_page() ) {
		return sprintf(
			/* translators: %s: site name. */
			__( '%s - We put ink on the island', 'magenta' ),
			get_bloginfo( 'name' )
		);
	}

	if ( is_singular() ) {
		return (string) get_the_title();
	}

	if ( is_post_type_archive( 'project' ) ) {
		return __( 'Selected work', 'magenta' );
	}

	if ( is_tax() || is_category() || is_tag() ) {
		return (string) single_term_title( '', false );
	}

	return (string) get_bloginfo( 'name' );
}

/**
 * Document title.
 *
 * add_theme_support( 'title-tag' ) alone left the front page titled with the
 * site name and nothing else - seven characters, which tells a searcher
 * nothing and wastes the single strongest on-page relevance signal there is.
 * Google renders roughly 50-60; these aim for 45-62 including the brand tail.
 */
function magenta_document_title( array $parts ): array {
	if ( is_front_page() ) {
		return array(
			'title'   => __( 'Printing &amp; Graphic Design in Grand Cayman', 'magenta' ),
			'tagline' => get_bloginfo( 'name' ),
		);
	}

	if ( is_post_type_archive( 'project' ) ) {
		$parts['title'] = __( 'Print Work for Cayman Hotels, Restaurants &amp; Retail', 'magenta' );
	}

	if ( is_tax( 'service' ) ) {
		$parts['title'] = sprintf(
			/* translators: %s: service name, e.g. Screen Printing. */
			__( '%s in the Cayman Islands', 'magenta' ),
			single_term_title( '', false )
		);
	}

	if ( is_tax( 'sector' ) ) {
		$parts['title'] = sprintf(
			/* translators: %s: sector name, e.g. Hotels. */
			__( 'Printing for %s in Cayman', 'magenta' ),
			single_term_title( '', false )
		);
	}

	if ( is_singular( 'project' ) ) {
		$client = magenta_project_client();
		if ( $client ) {
			$parts['title'] = sprintf(
				/* translators: 1: project title, 2: client name. */
				__( '%1$s - Print Project for %2$s', 'magenta' ),
				get_the_title(),
				$client
			);
		}
	}

	// Site name always closes the title; drop the separate tagline part so it
	// does not run past what Google will render.
	$parts['site'] = get_bloginfo( 'name' );
	unset( $parts['tagline'] );

	return $parts;
}
add_filter( 'document_title_parts', 'magenta_document_title' );

/**
 * Separator between title and brand.
 */
function magenta_title_separator(): string {
	return '·';
}
add_filter( 'document_title_separator', 'magenta_title_separator' );

/**
 * Keyword terms for the current view.
 *
 * Built from the same topic list the entity graph uses, with the two or three
 * geo-qualified phrases the studio actually competes for, and whatever the
 * current archive or project is about pushed to the front.
 *
 * Worth being straight about what this tag is: Google has ignored
 * meta keywords as a ranking signal since 2009 and has said so on the record,
 * and Bing treats it at best as a spam signal. It is emitted because audit
 * tools still check for it and because some smaller crawlers and content
 * classifiers do read it - not because it will move a position. The terms that
 * do work are the ones in the title, the headings and the entity graph.
 *
 * @return array<int, string>
 */
function magenta_keywords(): array {
	$terms = array(
		'Printing Cayman Islands',
		'Print Production Grand Cayman',
		'Graphic Design Cayman',
	);

	// The current view leads, when it has a subject of its own.
	if ( is_tax( 'service' ) || is_tax( 'sector' ) ) {
		array_unshift( $terms, (string) single_term_title( '', false ) );
	} elseif ( is_singular( 'project' ) ) {
		$client = magenta_project_client();
		if ( $client ) {
			array_unshift( $terms, $client );
		}
	}

	$terms = array_merge( $terms, magenta_knows_about() );

	// A long tail here reads as stuffing to anything that does parse it.
	$terms = array_slice( array_values( array_unique( array_filter( $terms ) ) ), 0, 12 );

	/**
	 * Filter the keyword terms.
	 *
	 * @param array $terms Keyword phrases.
	 */
	return apply_filters( 'magenta_keywords', $terms );
}

function magenta_print_meta(): void {
	static $printed = false;
	if ( $printed ) {
		return;
	}
	$printed = true;

	$url         = magenta_current_url();
	$title       = magenta_share_title();
	$description = magenta_meta_description();
	$image       = magenta_share_image();
	$is_project  = is_singular( 'project' );

	$tags = array();

	$tags[] = sprintf( '<meta name="description" content="%s">', esc_attr( $description ) );
	$tags[] = sprintf( '<link rel="canonical" href="%s">', esc_url( $url ) );
	$tags[] = sprintf( '<meta name="keywords" content="%s">', esc_attr( implode( ', ', magenta_keywords() ) ) );

	/*
	 * Author and publisher.
	 *
	 * The studio authors and publishes its own site, so both resolve to the
	 * organisation rather than to a person. These two tags exist because audit
	 * tools look for them; the signal search engines and AI assistants
	 * actually resolve is the publisher property on the WebSite node in
	 * inc/schema.php, which points at the Organization entity by @id. A meta
	 * name of "publisher" was never part of any spec - the standardised form
	 * was <link rel="publisher">, which Google retired with Google+.
	 */
	$tags[] = sprintf( '<meta name="author" content="%s">', esc_attr( get_bloginfo( 'name' ) ) );
	$tags[] = sprintf( '<meta name="publisher" content="%s">', esc_attr( get_bloginfo( 'name' ) ) );

	/* ----------------------------------------------------------- Open Graph */
	$tags[] = sprintf( '<meta property="og:type" content="%s">', $is_project ? 'article' : 'website' );
	$tags[] = sprintf( '<meta property="og:site_name" content="%s">', esc_attr( get_bloginfo( 'name' ) ) );
	$tags[] = sprintf( '<meta property="og:title" content="%s">', esc_attr( $title ) );
	$tags[] = sprintf( '<meta property="og:description" content="%s">', esc_attr( $description ) );
	$tags[] = sprintf( '<meta property="og:url" content="%s">', esc_url( $url ) );
	$tags[] = '<meta property="og:locale" content="en_KY">';
	$tags[] = sprintf( '<meta property="og:image" content="%s">', esc_url( $image['url'] ) );
	$tags[] = sprintf( '<meta property="og:image:secure_url" content="%s">', esc_url( $image['url'] ) );
	$tags[] = sprintf( '<meta property="og:image:width" content="%d">', $image['width'] );
	$tags[] = sprintf( '<meta property="og:image:height" content="%d">', $image['height'] );
	$tags[] = sprintf( '<meta property="og:image:alt" content="%s">', esc_attr( $image['alt'] ) );
	/*
	 * Extension read off the path, not off the whole URL: a query string would
	 * defeat a naive suffix test. Deliberately not str_ends_with() - that is
	 * PHP 8.0 only, and this file runs on wp_head for every request, so on a
	 * 7.4 host it took the entire site down with a fatal rather than
	 * degrading. Nothing else in the theme needs 8.0.
	 */
	$path = (string) wp_parse_url( $image['url'], PHP_URL_PATH );
	$ext  = strtolower( pathinfo( $path, PATHINFO_EXTENSION ) );

	$types = array(
		'png'  => 'image/png',
		'webp' => 'image/webp',
		'gif'  => 'image/gif',
	);

	$tags[] = sprintf(
		'<meta property="og:image:type" content="%s">',
		isset( $types[ $ext ] ) ? $types[ $ext ] : 'image/jpeg'
	);

	if ( $is_project ) {
		$tags[] = sprintf( '<meta property="article:published_time" content="%s">', esc_attr( get_the_date( DATE_W3C ) ) );
		$tags[] = sprintf( '<meta property="article:modified_time" content="%s">', esc_attr( get_the_modified_date( DATE_W3C ) ) );
	}

	/* -------------------------------------------------------------- Twitter */
	$tags[] = '<meta name="twitter:card" content="summary_large_image">';
	$tags[] = sprintf( '<meta name="twitter:title" content="%s">', esc_attr( $title ) );
	$tags[] = sprintf( '<meta name="twitter:description" content="%s">', esc_attr( $description ) );
	$tags[] = sprintf( '<meta name="twitter:image" content="%s">', esc_url( $image['url'] ) );
	$tags[] = sprintf( '<meta name="twitter:image:alt" content="%s">', esc_attr( $image['alt'] ) );

	/* ------------------------------------------------------------ image_src
	   Legacy, but still what several link-preview scrapers look for first. */
	$tags[] = sprintf( '<link rel="image_src" href="%s">', esc_url( $image['url'] ) );

	echo "\n" . implode( "\n", $tags ) . "\n";
}
add_action( 'wp_head', 'magenta_print_meta', 5 );

/**
 * Stop WordPress emitting its own canonical alongside ours.
 */
remove_action( 'wp_head', 'rel_canonical' );
